# Generated by Django 2.1.8 on 2020-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_inventory', '0002_remove_blade_blade_nvme_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='blade_mini_storage',
            field=models.CharField(max_length=30),
        ),
    ]
