# Generated by Django 2.1.8 on 2020-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_inventory', '0003_auto_20200327_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='blade_storage_info',
            field=models.CharField(max_length=150),
        ),
    ]
