# Generated by Django 2.1.8 on 2020-03-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_inventory', '0004_auto_20200327_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='blade_memory_info',
            field=models.CharField(max_length=150),
        ),
    ]
