# Generated by Django 2.1.8 on 2020-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qali_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_bios_name', models.CharField(max_length=30)),
                ('q_blade_name', models.CharField(max_length=16)),
                ('q_case_name', models.CharField(max_length=48)),
                ('q_case_result', models.CharField(max_length=10)),
                ('q_case_link', models.CharField(max_length=150, unique=True)),
                ('q_comments', models.CharField(default='qali', max_length=16)),
                ('q_origin_link', models.CharField(default='link', max_length=100)),
                ('q_python_ver', models.CharField(default='2.7.17', max_length=7)),
                ('q_abundle_version', models.CharField(default='UCSM', max_length=16)),
                ('q_project_version', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=48, unique=True)),
                ('t_folder_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucs_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
