# Generated by Django 2.1.8 on 2020-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200227_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qali_result',
            name='q_python_ver',
            field=models.CharField(default='2.7.17', max_length=50),
        ),
    ]
